POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Giri",
  "name": "Greeshma",
  "password": "123456",
  "gender": "Female",
  "location": "Detroit"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "Giri",
    "password": "123456"
}

###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "Giri",
  "oldPassword": "asdfgh",
  "newPassword": "123456"
}